name: ci-autotrade-sales-api

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

env:
  MONGODB_URL: ${{secrets.MONGODB_URL}}
  REQUESTS_FROM_PAYMENT_GATEWAY_TO_SALES_API_KEY: ${{secrets.REQUESTS_FROM_PAYMENT_GATEWAY_TO_SALES_API_KEY}}
  REQUESTS_FROM_ADMIN_TO_SALES_API_KEY: ${{secrets.REQUESTS_FROM_ADMIN_TO_SALES_API_KEY}}
  REQUESTS_FROM_SALES_TO_ADMIN_API_KEY: ${{secrets.REQUESTS_FROM_SALES_TO_ADMIN_API_KEY}}
  ADMIN_SERVICE_BASE_URL: ${{secrets.ADMIN_SERVICE_BASE_URL}}

jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: sudo apt-get update
      - run: sudo apt-get --no-install-recommends --no-upgrade -y install python3-pip
      - run: pip install -r requirements.txt
      - run: python -m pytest --cov=src
      - run: coverage report --fail-under=80
